# Site settings
title: Twins Onboard
description: Modern-Blog A Elegant template for Jekyll
keywords: Twins, Blogging, Fun
author: Shruti
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.twinsonboard.in" # the base hostname & protocol for your site
