# Site settings
title: Twins Onboard
description: Life with inscrutable twin girls
keywords: Twins, Blogging, Fun
author: Shruti
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.twinsonboard.in" # the base hostname & protocol for your site
